# Generated by Django 5.0.1 on 2024-03-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='distance_travelled',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
