# Generated by Django 5.0.1 on 2024-03-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_bikes_distance_travelled_alter_bikes_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikes',
            name='model_object',
        ),
        migrations.AddField(
            model_name='bikes',
            name='year',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bikes',
            name='cubic_capacity',
            field=models.CharField(max_length=200),
        ),
    ]
